project:
  type: website
  output-dir: docs

website:
  title: "posit::conf(2023)"
  site-url: https://posit-conf-2023.github.io/website
  description: "posit::conf(2023) workshops"

  repo-url: https://github.com/posit-conf-2023/workshops
  repo-actions: [edit, issue]

  open-graph: true

  navbar:
    background: "#447099"
    right:
      - icon: github
        href: https://github.com/posit-conf-2023/workshops
    left:
      - text: Workshops
        href: index.qmd
      - text: Pathways
        href: pathways.qmd

format:
  html:
    mainfont: "Atkinson Hyperlegible"
    published-title: "Starts on"
    author-title: "Instructor"
    description-title: "Length"
    theme: style.scss
    linkcolor: "#447099"

editor: visual
